import { render, type TemplateContext } from "../../template/engine.js";

const TEMPLATE = `# Project Analysis: {{projectName}}

Generated by agent-harness static analysis on {{generatedDate}}.

## Project Identity

- **Type**: {{projectType}}
- **Language**: {{projectLanguage}}
{{#if hasFramework}}- **Framework**: {{projectFramework}}{{/if}}
- **Detection signals**: {{projectSignals}}

{{#if hasWorkspacePackages}}## Workspace packages

Detected monorepo / workspace package paths (relative to repo root):

{{#each workspacePackageLines}}
{{.}}
{{/each}}

{{/if}}
## Directory Structure

{{#each directoryLines}}
{{.}}
{{/each}}

## Already Extracted Skills (Static Analysis)

{{#each skillLines}}
{{.}}
{{/each}}

## Gaps for AI Extraction

The static analysis above only covers surface-level patterns. The following areas require reading source code:

### Technical Gaps
- Architecture patterns and module boundaries
- Error handling conventions
- Data access and state management patterns
- Security patterns (auth, validation, sanitization)
- Performance patterns and optimization conventions

### Business Gaps
- Domain model and entity relationships
- Business rule patterns and validation logic
- API contract conventions
- User-facing content guidelines
`;

export interface ProjectAnalysisTemplateContext extends TemplateContext {
  projectName: string;
  generatedDate: string;
  projectType: string;
  projectLanguage: string;
  hasFramework: boolean;
  projectFramework?: string;
  projectSignals: string;
  directoryLines: string[];
  skillLines: string[];
  hasWorkspacePackages: boolean;
  workspacePackageLines: string[];
}

export function renderProjectAnalysisDoc(ctx: ProjectAnalysisTemplateContext): string {
  return render(TEMPLATE, ctx);
}
