import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { parse as parseYaml } from "yaml";
import type { GeneratedFile } from "../tool-adapters/types.js";
import { loadHarnessConfig } from "../config/load-harness-config.js";
import { mergeSkill } from "../skill-extraction/merger.js";
import { parseSkillFile } from "../skill-extraction/parser.js";
import { buildParsedSkillForMerge, isHarnessMergeableSkillPath } from "../skill-extraction/skill-build.js";
import { resolve as resolveScaffold } from "./resolver.js";

export interface DiffResult {
  unchanged: string[];
  modified: string[];
  added: string[];
  removed: string[];
}

export function diffPlan(
  cwd: string,
  newFiles: GeneratedFile[],
  previousFiles?: string[],
): DiffResult {
  const unchanged: string[] = [];
  const modified: string[] = [];
  const added: string[] = [];

  const newPaths = new Set<string>();

  for (const file of newFiles) {
    newPaths.add(file.path);
    const absPath = resolve(cwd, file.path);

    if (!existsSync(absPath)) {
      added.push(file.path);
      continue;
    }

    try {
      const existing = readFileSync(absPath, "utf-8");
      if (existing === file.content) {
        unchanged.push(file.path);
      } else {
        modified.push(file.path);
      }
    } catch {
      added.push(file.path);
    }
  }

  const removed: string[] = [];
  if (previousFiles) {
    for (const prev of previousFiles) {
      if (!newPaths.has(prev)) {
        removed.push(prev);
      }
    }
  }

  return { unchanged, modified, added, removed };
}

export type DriftStatus = "modified" | "missing" | "extra";

export interface DriftEntry {
  path: string;
  status: DriftStatus;
  hint: string;
}

export interface DriftReport {
  clean: boolean;
  drifted: DriftEntry[];
  /** Paths expected by the plan but absent on disk. */
  missing: string[];
  /** Paths listed in `generated_files` but no longer in the harness plan. */
  extra: string[];
}

/** Reuse the date embedded in PROJECT-ANALYSIS.md so re-resolve matches on-disk skill docs (date would otherwise change daily). */
function readDriftAnchorDate(cwd: string): string | undefined {
  const p = resolve(cwd, ".harness/skills/PROJECT-ANALYSIS.md");
  if (!existsSync(p)) return undefined;
  try {
    const text = readFileSync(p, "utf-8");
    const m = text.match(/Generated by harn static analysis on (\d{4}-\d{2}-\d{2})/);
    return m?.[1];
  } catch {
    return undefined;
  }
}

function deepSortKeys(obj: unknown): unknown {
  if (obj === null || typeof obj !== "object") return obj;
  if (Array.isArray(obj)) return obj.map(deepSortKeys);
  const sorted: Record<string, unknown> = {};
  for (const k of Object.keys(obj as object).sort()) {
    sorted[k] = deepSortKeys((obj as Record<string, unknown>)[k]);
  }
  return sorted;
}

/** Drop undefined keys so JSON round-trips match YAML parse variants. */
function stripUndefinedDeep(obj: unknown): unknown {
  if (obj === null || typeof obj !== "object") return obj;
  if (Array.isArray(obj)) return obj.map(stripUndefinedDeep);
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj as Record<string, unknown>)) {
    if (v === undefined) continue;
    out[k] = stripUndefinedDeep(v);
  }
  return out;
}

function harnessConfigYamlEquivalent(disk: string, canonical: string): boolean {
  try {
    const da = parseYaml(disk) as Record<string, unknown>;
    const db = parseYaml(canonical) as Record<string, unknown>;
    const norm = (o: Record<string, unknown>) => {
      const out = { ...o };
      if (Array.isArray(out.generated_files)) {
        out.generated_files = [...(out.generated_files as string[])].sort() as unknown as string[];
      }
      return out;
    };
    const sa = deepSortKeys(stripUndefinedDeep(norm(da)));
    const sb = deepSortKeys(stripUndefinedDeep(norm(db)));
    return JSON.stringify(sa) === JSON.stringify(sb);
  } catch {
    return disk === canonical;
  }
}

/** Same notion of equality as generateFiles (merge for mergeable harness SKILL.md paths, YAML-tolerant config). */
function fileMatchesCanonical(cwd: string, file: GeneratedFile): boolean {
  const absPath = resolve(cwd, file.path);
  if (!existsSync(absPath)) return false;
  const disk = readFileSync(absPath, "utf-8");
  if (file.path === ".harness/config.yaml") {
    return harnessConfigYamlEquivalent(disk, file.content);
  }
  if (isHarnessMergeableSkillPath(file.path)) {
    try {
      const existingParsed = parseSkillFile(disk);
      const generatedParsed = buildParsedSkillForMerge(file);
      const decision = mergeSkill(existingParsed, generatedParsed, "overwrite");
      return decision.content === disk;
    } catch {
      return false;
    }
  }
  return disk === file.content;
}

/**
 * Compares the canonical scaffold output for the current .harness/config.yaml
 * with files on disk (and optional generated_files list for orphan detection).
 */
export function detectDrift(cwd: string): DriftReport {
  const loaded = loadHarnessConfig(cwd);
  if (!loaded.valid || !loaded.config) {
    return { clean: true, drifted: [], missing: [], extra: [] };
  }

  const anchorDate = readDriftAnchorDate(cwd);
  const config = loaded.config;
  const wf = config.workflows;
  const commands =
    wf.commands && Object.keys(wf.commands).length > 0 ? wf.commands : undefined;
  const verificationChecks =
    wf.verification.checks && wf.verification.checks.length > 0
      ? wf.verification.checks
      : undefined;

  const plan = resolveScaffold({
    cwd,
    projectName: config.project.name,
    projectType: config.project.type,
    tools: config.tools,
    toolpacks: config.toolpacks ?? [],
    skipDocs: config.skip_docs ?? false,
    ...(commands ? { commands } : {}),
    ...(verificationChecks ? { verificationChecks } : {}),
    ...(config.custom_rules !== undefined ? { customRulesFromConfig: config.custom_rules } : {}),
    ...(anchorDate ? { generatedDateOverride: anchorDate } : {}),
  });

  const previousFiles = Array.isArray(config.generated_files) ? config.generated_files : undefined;
  const newPaths = new Set(plan.files.map((f) => f.path));

  const drifted: DriftEntry[] = [];
  const missing: string[] = [];
  const extra: string[] = [];

  for (const file of plan.files) {
    const absPath = resolve(cwd, file.path);
    if (!existsSync(absPath)) {
      missing.push(file.path);
      drifted.push({
        path: file.path,
        status: "missing",
        hint: "Expected file is missing on disk.",
      });
      continue;
    }
    if (!fileMatchesCanonical(cwd, file)) {
      drifted.push({
        path: file.path,
        status: "modified",
        hint: "File content differs from harness canonical output.",
      });
    }
  }

  if (previousFiles) {
    for (const prev of previousFiles) {
      if (!newPaths.has(prev)) {
        extra.push(prev);
        drifted.push({
          path: prev,
          status: "extra",
          hint: "File was listed in generated_files but is no longer in the harness plan.",
        });
      }
    }
  }

  const clean = drifted.length === 0;
  return { clean, drifted, missing, extra };
}
