import type { ToolId } from "../tool-adapters/types.js";
import type { Toolpack } from "../toolpacks/registry.js";
import { ALL_TOOL_IDS } from "../tool-adapters/types.js";

const TOOL_DOC_LINKS: Partial<Record<ToolId, string>> = {
  cursor: "https://docs.cursor.com/context/mcp",
  "claude-code": "https://docs.anthropic.com/en/docs/claude-code",
  copilot: "https://docs.github.com/en/copilot",
  codex: "https://developers.openai.com/codex",
  opencode: "https://opencode.ai/docs",
  windsurf: "https://docs.windsurf.com",
  trae: "https://www.trae.ai/docs",
  augment: "https://docs.augmentcode.com",
};

/** Snippet hints only — users paste into each tool's native config location. */
const SNIPPET_HINTS: Partial<Record<ToolId, string>> = {
  cursor: "`.cursor/mcp.json` — `mcpServers` object (see `agent-harness mcp merge --help`).",
  "claude-code": "Claude Code MCP / plugins per vendor docs.",
  copilot: "`.github/copilot-instructions.md` + GitHub Copilot settings.",
  codex: "`.codex/config.toml` and Codex MCP docs.",
  opencode: "`opencode.json` skills / MCP per OpenCode docs.",
  windsurf: "`.windsurf/rules/` and Windsurf MCP UI.",
  trae: "`.trae/rules/` and Trae docs.",
  augment: "`augment-guidelines.md` and Augment docs.",
};

function unionTools(selected: ToolId[], packs: Toolpack[]): ToolId[] {
  const fromPacks = new Set<ToolId>();
  for (const p of packs) {
    for (const t of p.relevantTools) {
      fromPacks.add(t);
    }
  }
  const out = new Set<ToolId>([...selected, ...fromPacks]);
  return ALL_TOOL_IDS.filter((id) => out.has(id));
}

export function buildRecommendedToolsMarkdown(
  projectName: string,
  selectedTools: ToolId[],
  resolvedPacks: Toolpack[],
): string {
  const tools = unionTools(selectedTools, resolvedPacks);
  const rows = tools.map((id) => {
    const doc = TOOL_DOC_LINKS[id] ?? "(see vendor documentation)";
    const hint = SNIPPET_HINTS[id] ?? "See vendor docs for MCP / rules paths.";
    return `| \`${id}\` | ${doc} | ${hint} |`;
  });

  const packLines =
    resolvedPacks.length > 0
      ? resolvedPacks.map((p) => `- **${p.id}** (${p.packSource}) — relevant tools: ${p.relevantTools.join(", ")}`).join("\n")
      : "_No optional toolpacks selected._";

  return `# Recommended tools & paste targets — ${projectName}

Static reference generated by **Agent Harness** (no runtime MCP fetch). Use official docs for authoritative config.

## Selected AI tools

| Tool | Documentation | Config / snippet hint |
|------|---------------|----------------------|
${rows.join("\n")}

## Toolpacks in this project

${packLines}

## Validation (optional)

- Cursor \`mcp.json\` can be checked against the schema shipped with \`cc-agent-harness\` (see package \`schemas/cursor-mcp.json\`).
- Keep verification commands in \`.harness/config.yaml\` and run \`agent-harness verify\`.
`;
}
